'use strict';

const constants = {
  NEW_INTERVENTION: 'NEW_INTERVENTION',
  FIELDED_INTERVENTION: 'FIELDED_INTERVENTION',
  ERASER: 'ERASER',
  BADGE: 'BADGE',

  BOARD_NATIVE_WIDTH: 2000,
  BOARD_NATIVE_HEIGHT: 740,
  HEIGHT_RATIO: 740 / 2000
};

export default constants;
